# reminder: don't forget to add the necessary parameters to medium + long terms!

short:
  input_window: 672
  min_input_window: 96
  output_horizon: 96
  target_column: "actual_load"
  early_stopping_patience: 5
  epochs: 50            
  batch_size: 64            
  learning_rate: 0.001  
  train_split: 0.8
  val_split: 0.1
  run_tag: "short_exog_baseline" 

  # LSTM
  lags: [1, 2, 96, 192, 288, 672]
  feature_scaler: "MinMax"     
  target_scaler: "MinMax"    
  lstm_units: 64      
  dropout_rate: 0.2       
  loss_function: "mae"
  exogenous_features: [ 
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag", 
      "temperature", "solar_capacity", "solar_generation", "wind_capacity", 
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation", 
      "wind_onshore_capacity", "wind_onshore_generation"
    ]

  # TFT
  hidden_size: 16              
  attention_head_size: 1     
  dropout: 0.1                 
  # log_interval: 10              # Used by TFT model, keep if needed, not usually tuned
  # reduce_on_plateau_patience: 4 # Used by TFT model, keep if needed, not usually tuned
  gradient_clip_val: 0.1       
  # log_every_n_steps: 10         # For Trainer's logger, not typically tuned

  # HPO
  epochs_hpo: 15
  early_stopping_patience_hpo: 3
  hpo_pruner_warmup: 2
  # hpo_timeout_seconds: 3600 # Optional

medium:
  input_window: 2016         
  output_horizon: 672    
  target_column: "actual_load"   
  early_stopping_patience: 5
  epochs: 50
  batch_size: 64
  learning_rate: 0.001
  train_split: 0.8            
  val_split: 0.1          
  run_tag: "medium_exog_baseline" 

#LSTM specific parameters
  lags: [1, 96, 672, 1344, 2016]
  feature_scaler: "MinMax"     
  target_scaler: "MinMax"
  lstm_units: 64      
  dropout_rate: 0.2              
  loss_function: "mae"
  exogenous_features: [ 
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag", 
      "temperature", "solar_capacity", "solar_generation", "wind_capacity", 
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation", 
      "wind_onshore_capacity", "wind_onshore_generation"
    ]

long:
  input_window: 4032             
  output_horizon: 2880           
  target_column: "actual_load"  
  early_stopping_patience: 5
  epochs: 50
  batch_size: 4
  learning_rate: 0.001
  train_split: 0.8             
  val_split: 0.1           
  run_tag: "long_exog_baseline"  

#LSTM specific parameters
  lags: [1, 96, 672, 1440, 2880] 
  feature_scaler: "MinMax"     
  target_scaler: "MinMax"
  lstm_units: 64      
  dropout_rate: 0.2              
  loss_function: "mae"
  exogenous_features: [
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag", 
      "temperature", "solar_capacity", "solar_generation", "wind_capacity", 
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation", 
      "wind_onshore_capacity", "wind_onshore_generation"
    ]