short:
  input_window: 672
  output_horizon: 96
  min_input_window: 96
  target_column: "actual_load"
  train_split: 0.8
  val_split: 0.1
  num_workers: 2

  # LSTM (HPO)
  run_tag: "baseline_final_lstm_short"
  batch_size: 32
  early_stopping_patience: 2
  epochs: 7
  # learning rate

  # HPO parameters
  epochs_hpo: 15
  early_stopping_patience_hpo: 3
  hpo_pruner_warmup: 2

  # LSTM Parameters
  learning_rate: 0.001
  lags: [1, 2, 96, 192, 288, 672]
  feature_scaler: "MinMax"
  target_scaler: "MinMax"
  lstm_units: 32
  dropout_rate: 0.1
  loss_function: "mae"
  exogenous_features: [
      "hour_sin", "hour_cos", "weekday_sin", "weekday_cos", "month_sin", "month_cos",
      "is_daylight", "year", "weekend_flag", "holiday_flag", "temperature",
      "solar_capacity", "solar_generation", "wind_capacity", "wind_generation",
      "wind_offshore_capacity", "wind_offshore_generation", "wind_onshore_capacity", "wind_onshore_generation"
    ]

  # TFT Parameters
  run_tag_tft: "baseline_final_tft_short"
  hidden_size: 16
  attention_head_size: 1
  dropout: 0.1
  gradient_clip_val: 0.1
  exogenous_features_tft: [
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag",
      "temperature", "solar_capacity", "solar_generation", "wind_capacity",
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation",
      "wind_onshore_capacity", "wind_onshore_generation"
    ]

medium:
  input_window: 1344
  output_horizon: 672
  min_input_window: 96
  target_column: "actual_load"
  train_split: 0.8
  val_split: 0.1
  num_workers: 2

  # Short tuned parameters
  run_tag: "baseline_final_lstm_medium"
  early_stopping_patience: 2
  epochs: 7
  batch_size: 32

  # HPO Parameters
  epochs_hpo: 15
  early_stopping_patience_hpo: 3
  hpo_pruner_warmup: 2

  # LSTM parameters
  learning_rate: 0.001
  lags: [1, 96, 672, 1344]
  feature_scaler: "MinMax"
  target_scaler: "MinMax"
  lstm_units: 32
  dropout_rate: 0.1
  loss_function: "mae"
  exogenous_features: [
      "hour_sin", "hour_cos", "weekday_sin", "weekday_cos", "month_sin", "month_cos",
      "is_daylight", "year", "weekend_flag", "holiday_flag", "temperature",
      "solar_capacity", "solar_generation", "wind_capacity", "wind_generation",
      "wind_offshore_capacity", "wind_offshore_generation", "wind_onshore_capacity", "wind_onshore_generation"
    ]

  # TFT parameters
  run_tag_tft: "baseline_final_tft_medium"
  hidden_size: 16
  attention_head_size: 1
  dropout: 0.1
  gradient_clip_val: 0.1
  exogenous_features_tft: [
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag",
      "temperature", "solar_capacity", "solar_generation", "wind_capacity",
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation",
      "wind_onshore_capacity", "wind_onshore_generation"
    ]

long:
  input_window: 672
  output_horizon: 2880
  min_input_window: 96
  target_column: "actual_load"
  train_split: 0.8
  val_split: 0.1
  num_workers: 2

  run_tag: "baseline_final_lstm_long"
  epochs: 7
  early_stopping_patience: 2
  batch_size: 4

  lags: [1, 96, 672]
  feature_scaler: "MinMax"
  target_scaler: "MinMax"
  lstm_units: 32
  dropout_rate: 0.1
  loss_function: "mae"
  exogenous_features: [
      "hour_sin", "hour_cos", "weekday_sin", "weekday_cos", "month_sin", "month_cos",
      "is_daylight", "year", "weekend_flag", "holiday_flag", "temperature",
      "solar_capacity", "solar_generation", "wind_capacity", "wind_generation",
      "wind_offshore_capacity", "wind_offshore_generation", "wind_onshore_capacity", "wind_onshore_generation"
    ]

  run_tag_tft: "baseline_final_tft_long"
  hidden_size: 16
  attention_head_size: 1
  dropout: 0.1
  gradient_clip_val: 0.1
  exogenous_features_tft: [
      "hour", "is_daylight", "month", "year", "weekday", "weekend_flag", "holiday_flag",
      "temperature", "solar_capacity", "solar_generation", "wind_capacity",
      "wind_generation", "wind_offshore_capacity", "wind_offshore_generation",
      "wind_onshore_capacity", "wind_onshore_generation"
    ]